version: '3.1'

services:
  db:
    container_name: postgres-test-immo
    image: postgres:13.0-alpine
    environment:
        POSTGRES_PASSWORD: test
        POSTGRES_USER: test
        POSTGRES_DB: immodev
        PGDATA: /var/lib/postgresql/data
    ports:
      - 6004:5432
    volumes:
      - ./docker:/var/lib/postgresql/data
  app:
    container_name: immo-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    network_mode: host
